### PR TITLE
Adds Connection ID to log statements

### PR DESCRIPTION
**Pull request by markwoon**
Adds Connection ID to log statements.

### CODE REVIEW

**Comment by adrianshum** [comment]
I am a bit hesitated in the way the change is implemented.  
1. Connection ID is passed around everywhere which makes methods' signature confusing/unclear
2. I still think Connection ID should be something optional to display, hence I insist to make use of MDC (and I think it is what MDC aimed for), so that user can turn on/off connection ID by a proper log message pattern.
3. Some irrelevant changes are made, which cause behavioral difference (e.g. some logs are removed when constructing connection).

However thanks for this contribution and I believe I can take this as reference to produce something similar soon :)

**Comment by adrianshum** [comment]
I have deployed a new version with MDC-based implementation of Connection ID.  Would you mind have a try on that?  Please use version 2.1-BETA1.

You simply need to add to your log pattern a `%X` or `%X{jdbcdslog.connectionId}` in order to include all MDC or connection ID entry of MDC.

Result looks like

    2015-01-27 10:17:47,779 [INFO ] [jdbcdslog.connectionId=1] main - o.j.ConnectionLogger: Connected to URL jdbc:oracle:thin:@foo.bar.com:1521:dbfoo for user USER_FOO
    2015-01-27 10:17:47,959 [INFO ] [jdbcdslog.connectionId=1] main - o.j.StatementLogger: java.sql.PreparedStatement.execute: select * from foo where f1 = ? and f2 = ? parameters: {1=6, 2=4}
    at com.fil.ims.TestMainJdbcDsLog.main(TestMainJdbcDsLog.java:58)
    Elapsed Time: 0.073786392 s.

Please let me know if there is any bug in this implementation :)  If not, I am going to make an 2.1 release

**Comment by markwoon** [comment]
Apologies for the late response. 

My only issue with the MDC approach is that it gets applied to _all_ log statements, and I only want/need that information when logging SQL.

**Comment by adrianshum** [comment]
The information should be equivalently important for other log statement.  For example I see no reason why we should not include that in the result set logging.  

However I think you actually suggested something interesting.  We may look into how to make use of Marker, for example, to provide more information on the type of log message it is, and hence, provide more flexible control.

**Pull request closed without merging**
